apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dev-feed.fullname" . }}
  labels:
    {{- include "dev-feed.labels" . | nindent 4 }}
data:
  backend.properties: |
    {{- printf "datasource.url=%s" (include "dev-feed.databaseJdbcUrl" .) | nindent 4 }}
    {{- printf "datasource.driver=%s" (include "dev-feed.databaseJdbcDriver" .) | nindent 4 }}
    {{- if .Values.mariadb.enabled }}
      {{- printf "# Crawlers disabled here but deployed as independent Kubernetes CronJobs (1 per crawler service)" | nindent 4 }}
      {{- printf "crawlers.task.fetch-articles=false" | nindent 4 }}
    {{- else}}
      {{- printf "crawlers.task.fetch-articles=true" | nindent 4 }}
      {{- if .Values.crawlers.discoverdev_io.enabled }}
        {{- printf "crawlers.discoverdev_io.enabled=true" | nindent 4 }}
      {{- else}}
        {{- printf "crawlers.discoverdev_io.enabled=false" | nindent 4 }}
      {{- end}}
      {{- if .Values.crawlers.engineeringblogs_xyz.enabled }}
        {{- printf "crawlers.engineeringblogs_xyz.enabled=true" | nindent 4 }}
      {{- else}}
        {{- printf "crawlers.engineeringblogs_xyz.enabled=false" | nindent 4 }}
      {{- end}}
      {{- if .Values.crawlers.rm3l_org.enabled }}
        {{- printf "crawlers.rm3l_org.enabled=true" | nindent 4 }}
      {{- else}}
        {{- printf "crawlers.rm3l_org.enabled=false" | nindent 4 }}
      {{- end}}
    {{- end}}
    {{ printf "\n" }}
    {{- .Values.config | indent 4 }}
