{{- if or .Values.mariadb.enabled .Values.mongodb.enabled }}
{{- $kubeVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- if .Values.crawlers.discoverdev_io.enabled }}
{{/* discoverdev.io */}}
{{- if semverCompare ">=1.21-0" $kubeVersion -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "dev-feed.fullname" . }}-crawler-discoverdev-io
spec:
  schedule: "{{ .Values.crawlers.discoverdev_io.schedule }}"
  concurrencyPolicy: {{ .Values.crawlers.discoverdev_io.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.crawlers.discoverdev_io.startingDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.crawlers.discoverdev_io.activeDeadlineSeconds }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.crawlers.discoverdev_io.ttlSecondsAfterFinished }}
      template:
        spec:
          {{- with .Values.crawlers.discoverdev_io.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.crawlers.discoverdev_io.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
           {{- end }}
          serviceAccountName: {{ include "dev-feed.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.crawlers.discoverdev_io.podSecurityContext | nindent 12 }}

          initContainers:
          - name: wait-db-service
            image: busybox:1.28
            {{- if .Values.mariadb.enabled }}
            command: ['sh', '-c', "until nslookup {{ include "dev-feed.fullname" . }}-mariadb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "dev-feed.fullname" . }}-mariadb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
            {{- else }}
            command: ['sh', '-c', "until nslookup {{ include "dev-feed.fullname" . }}-mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "dev-feed.fullname" . }}-mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
            {{- end }}

          containers:
          - name: {{ include "dev-feed.fullname" . }}-crawler-discoverdev-io
            image: "{{ .Values.crawlers.discoverdev_io.image.repository }}:{{ .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.crawlers.discoverdev_io.image.pullPolicy }}
            env:
            {{- if .Values.mongodb.enabled }}
            - name: DATASOURCE_MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.mongodb.connectionString
            {{- else }}
            - name: DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.user
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.password
            {{- end }}
            args:
            {{- if .Values.mongodb.enabled }}
            - mongo
            - --mongo-connection-string=$(DATASOURCE_MONGODB_CONNECTION_STRING)
            {{- else }}
            - rdbms
            - --datasource-jdbc-driver={{ include "dev-feed.datasourceDriver" . }}
            - --datasource-jdbc-url={{ include "dev-feed.datasourceUrl" . }}
            - --datasource-user=$(DATASOURCE_USER)
            - --datasource-password=$(DATASOURCE_PASSWORD)
            {{- end }}
            - --article-max-age-days={{ .Values.crawlers.discoverdev_io.articleMaxAgeDays }}
          restartPolicy: {{ .Values.crawlers.discoverdev_io.restartPolicy }}

{{- end }}
---
{{- if .Values.crawlers.engineeringblogs_xyz.enabled }}
{{/* engineeringblogs.xyz */}}
{{- if semverCompare ">=1.21-0" $kubeVersion -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "dev-feed.fullname" . }}-crawler-engineeringblogs-xyz
spec:
  schedule: "{{ .Values.crawlers.engineeringblogs_xyz.schedule }}"
  concurrencyPolicy: {{ .Values.crawlers.engineeringblogs_xyz.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.crawlers.engineeringblogs_xyz.startingDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.crawlers.engineeringblogs_xyz.activeDeadlineSeconds }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.crawlers.engineeringblogs_xyz.ttlSecondsAfterFinished }}
      template:
        spec:
          {{- with .Values.crawlers.engineeringblogs_xyz.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.crawlers.engineeringblogs_xyz.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
           {{- end }}
          serviceAccountName: {{ include "dev-feed.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.crawlers.engineeringblogs_xyz.podSecurityContext | nindent 12 }}

          initContainers:
          - name: wait-db-service
            image: busybox:1.28
            {{- if .Values.mariadb.enabled }}
            command: ['sh', '-c', "until nslookup {{ include "dev-feed.fullname" . }}-mariadb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "dev-feed.fullname" . }}-mariadb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
            {{- else }}
            command: ['sh', '-c', "until nslookup {{ include "dev-feed.fullname" . }}-mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "dev-feed.fullname" . }}-mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
            {{- end }}

          containers:
          - name: {{ include "dev-feed.fullname" . }}-crawler-engineeringblogs-xyz
            image: "{{ .Values.crawlers.engineeringblogs_xyz.image.repository }}:{{ .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.crawlers.engineeringblogs_xyz.image.pullPolicy }}
            env:
            {{- if .Values.mongodb.enabled }}
            - name: DATASOURCE_MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.mongodb.connectionString
            {{- else }}
            - name: DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.user
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.password
            {{- end }}
            args:
            {{- if .Values.mongodb.enabled }}
            - mongo
            - --mongo-connection-string=$(DATASOURCE_MONGODB_CONNECTION_STRING)
            {{- else }}
            - rdbms
            - --datasource-jdbc-driver={{ include "dev-feed.datasourceDriver" . }}
            - --datasource-jdbc-url={{ include "dev-feed.datasourceUrl" . }}
            - --datasource-user=$(DATASOURCE_USER)
            - --datasource-password=$(DATASOURCE_PASSWORD)
            {{- end }}
            - --article-max-age-days={{ .Values.crawlers.engineeringblogs_xyz.articleMaxAgeDays }}
          restartPolicy: {{ .Values.crawlers.engineeringblogs_xyz.restartPolicy }}
{{- end }}
---
{{- if .Values.crawlers.rm3l_org.enabled }}
{{/* rm3l.org */}}
{{- if semverCompare ">=1.21-0" $kubeVersion -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "dev-feed.fullname" . }}-crawler-rm3l-org
spec:
  schedule: "{{ .Values.crawlers.rm3l_org.schedule }}"
  concurrencyPolicy: {{ .Values.crawlers.rm3l_org.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.crawlers.rm3l_org.startingDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.crawlers.rm3l_org.activeDeadlineSeconds }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.crawlers.rm3l_org.ttlSecondsAfterFinished }}
      template:
        spec:
          {{- with .Values.crawlers.rm3l_org.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.crawlers.rm3l_org.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
           {{- end }}
          serviceAccountName: {{ include "dev-feed.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.crawlers.rm3l_org.podSecurityContext | nindent 12 }}

          initContainers:
          - name: wait-db-service
            image: busybox:1.28
            {{- if .Values.mariadb.enabled }}
            command: ['sh', '-c', "until nslookup {{ include "dev-feed.fullname" . }}-mariadb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "dev-feed.fullname" . }}-mariadb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
            {{- else }}
            command: ['sh', '-c', "until nslookup {{ include "dev-feed.fullname" . }}-mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "dev-feed.fullname" . }}-mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
            {{- end }}

          containers:
          - name: {{ include "dev-feed.fullname" . }}-crawler-rm3l-org
            image: "{{ .Values.crawlers.rm3l_org.image.repository }}:{{ .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.crawlers.rm3l_org.image.pullPolicy }}
            env:
            {{- if .Values.mongodb.enabled }}
            - name: DATASOURCE_MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.mongodb.connectionString
            {{- else }}
            - name: DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.user
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.password
            {{- end }}
            args:
            {{- if .Values.mongodb.enabled }}
            - mongo
            - --mongo-connection-string=$(DATASOURCE_MONGODB_CONNECTION_STRING)
            {{- else }}
            - rdbms
            - --datasource-jdbc-driver={{ include "dev-feed.datasourceDriver" . }}
            - --datasource-jdbc-url={{ include "dev-feed.datasourceUrl" . }}
            - --datasource-user=$(DATASOURCE_USER)
            - --datasource-password=$(DATASOURCE_PASSWORD)
            {{- end }}
            - --article-max-age-days={{ .Values.crawlers.rm3l_org.articleMaxAgeDays }}
          restartPolicy: {{ .Values.crawlers.rm3l_org.restartPolicy }}
{{- end }}
{{- end }}
