apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-feed.fullname" . }}
  labels:
    {{- include "dev-feed.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "dev-feed.selectorLabels" . | nindent 4 }}
