apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-names-port-numbers.fullname" . }}
  labels:
    {{- include "service-names-port-numbers.labels" . | nindent 4 }}
data:
  service-names-port-numbers-app.properties:
    {{- toYaml .Values.config | indent 4 }}
